### ISSUE TITLE
为什么着色器项目会依赖梭子鱼？

### ISSUE THREAD

**Issue by endink** [JasonMa0012/JasonMaToonRenderPipeline#15]

**Comment by JasonMa0012** [comment]
内置一个风格迁移demo，你可以选择不使用

**Comment by endink** [comment]
额，不得不手动调整你的包文件，有空的话分离一下 repo 吧，对于没有使用梭子鱼的项目来说，这个 protobuff 版本比较旧~非常容易冲突

**Comment by JasonMa0012** [comment]
欢迎提交pr

**Comment by endink** [comment]
好的，晚点提交 PR, 因为依赖写在 package.json 里，只能手动调整，如果这个包打算长期升级的话这个问题就很麻烦，只能下载以后改，另外，非常棒的 shader ！感谢
