### ISSUE TITLE
我新建的工程，然后导入JTRP，根据教程写的，进行操作，但是重启工程有报错，且摄像机变蓝和场景变样，我是个小白，求解答

### ISSUE THREAD

**Issue by NarakoYo** [JasonMa0012/JasonMaToonRenderPipeline#16]
![image](https://user-images.githubusercontent.com/65006928/231232638-e6b90474-c9aa-4636-be13-59376953dbbe.png)

**Comment by NarakoYo** [comment]
在我上一个已有模型的工程内，在导入该插件后，材质全部丢失变紫，我查看材质球内容物是正常的

**Comment by JasonMa0012** [comment]
换unity2021
