### ISSUE TITLE
Group下的Textfield不能被focus

### ISSUE THREAD

**Issue by Ruka1998** [JasonMa0012/JasonMaToonRenderPipeline#3]
当脚本第一次更新成功并且操作的时候不会有这个问题，
需要先选中当前Scene内的其他Object，然后再回来激活当前材质面板，就会出现
https://user-images.githubusercontent.com/48833884/103646218-48cbc500-4f94-11eb-95d4-6acaf7466425.mp4
（这个链接似乎需要下载下来才能看到画面）

谢谢你写了这么好用的面板！

**Comment by JasonMa0012** [comment]
已知，不过近期没有更新的计划，以后有机会会重写

**Comment by JasonMa0012** [comment]
最近准备开工啦，可以先star一下新repo：https://github.com/JasonMa0012/LWGUI

**Comment by JasonMa0012** [comment]
https://github.com/JasonMa0012/LWGUI
