### ISSUE TITLE
Author's Issue: Please delete this repository or change to private repository.

### ISSUE THREAD

**Issue by Stereoarts** [JasonMa0012/JasonMaToonRenderPipeline#4]
I don't permit to upload my copyrights(codes, images, models, motions, and documents) to public space. Please delete this repository or change to private repository.

So you must check model / motion's licenses. Almost models and motions aren't permitted using without MMD and redistribution.

**Comment by Stereoarts** [comment]
And I was very tired for supporting.

**Comment by Stereoarts** [comment]
Again, please don't use public space.

**Comment by JasonMa0012** [comment]
I’m sorry to accidentally upload your plug-in, I have deleted it, deleted most of the third-party resources, and added a reference table.
Deleted all the history records at the same time, now this is like a new repository.
While JTRP has developed for some third party content, I will pay more attention to copyright issues in the future.
Apologize again.
