### ISSUE TITLE
Unity2020.3.22f1打开后出现prefab丢失且shader编译失败

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [JasonMa0012/JasonMaToonRenderPipeline#6]
git拉下来后直接用 2020.3.22f1 打开出现错误，运行后场景为空，截图如下

**Unity截图**
![Unity截图](https://github.com/Misaka-Mikoto-Tech/InjectFix_IL2CPP/blob/master/Pic/Unity2020.3.22f1.png?raw=true)

**文件差异对比**
![差异对比](https://github.com/Misaka-Mikoto-Tech/InjectFix_IL2CPP/blob/master/Pic/%E6%89%93%E5%BC%80%E5%90%8E%E4%BA%A7%E7%94%9F%E7%9A%84%E6%96%87%E4%BB%B6%E5%B7%AE%E5%88%AB.png?raw=true)

**Comment by JasonMa0012** [comment]
已修复
