### ISSUE TITLE
SampleDrawer.shader 编译错误

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [JasonMa0012/JasonMaToonRenderPipeline#7]
更新到 7c5b7b882b0d3b554f1d17a29e8e392129575e80 后 SampleDrawer.shader 编译错误

**Unity截图**
![Unity截图](https://github.com/Misaka-Mikoto-Tech/InjectFix_IL2CPP/blob/master/Pic/SampleDrawerError.png?raw=true)

**Comment by JasonMa0012** [comment]
fixed
